// Database of Medical Spare Parts & Equipment - Nakhonping Hospital
    // Complies with SMM 07-1:2024 and CMMS Specifications
    // V3: inStock reset to 0 — กรอกยอดจริงผ่านระบบรับเข้า

    const INITIAL_PARTS = [
      {
        code: "SR-SPO2-001",
        name: "Adult Finger SpO2 Sensor Original Masimo LNCS DC-I (#1863)",
        description: "Masimo SpO2 sensor for patient monitors with LNCS connector.",
        manufacturer: "Masimo",
        equipmentModels: ["Masimo Radical-7", "Philips IntelliVue MX450"],
        inStock: 0,
        unitPrice: 8200.00,
        minStock: 5,
        maxStock: 50,
        reorderPoint: 10,
        reorderQty: 25,
        location: "Cabinet A - Shelf 2 - Box 01",
        supplierName: "SR Science & Service Co., Ltd. (ร้านเอสอาร์.ชายน์แอนด์เซอร์วิส)",
        supplierContact: "081-589-4409",
        purchaseDate: "2024-12-04",
        expiryDate: "2027-12-04",
        leadTime: 14,
        repairFreq: 4,
      },
      {
        code: "SR-SPO2-002",
        name: "TruSignal Integrated Sensor SpO2 Soft Adult, 13 ft (4m) (#TS-SA4-GE)",
        description: "TruSignal technology integrated SpO2 soft reusable sensor.",
        manufacturer: "Datex-Ohmeda/GE Healthcare",
        equipmentModels: ["GE Carescape B650", "GE Carescape B450"],
        inStock: 0,
        unitPrice: 8000.00,
        minStock: 2,
        maxStock: 20,
        reorderPoint: 4,
        reorderQty: 10,
        location: "Cabinet A - Shelf 2 - Box 02",
        supplierName: "SR Science & Service Co., Ltd. (ร้านเอสอาร์.ชายน์แอนด์เซอร์วิส)",
        supplierContact: "081-589-4409",
        purchaseDate: "2024-12-04",
        expiryDate: "2028-12-04",
        leadTime: 30,
        repairFreq: 2,
      },
      {
        code: "SR-SPO2-003",
        name: "Adult Finger SpO2 Sensor Original Covidien Nellcor (#DS100A)",
        description: "Nellcor OxiMax reusable SpO2 finger sensor, clip style.",
        manufacturer: "Covidien Nellcor",
        equipmentModels: ["Nellcor PM10N", "Mindray BeneVision N12", "GE Carescape B450"],
        inStock: 0,
        unitPrice: 5100.00,
        minStock: 15,
        maxStock: 120,
        reorderPoint: 25,
        reorderQty: 60,
        location: "Cabinet B - Shelf 1 - Box 01",
        supplierName: "SR Science & Service Co., Ltd. (ร้านเอสอาร์.ชายน์แอนด์เซอร์วิส)",
        supplierContact: "081-589-4409",
        purchaseDate: "2024-12-04",
        expiryDate: "2027-12-04",
        leadTime: 10,
        repairFreq: 12,
      },
      {
        code: "SR-SPO2-004",
        name: "Finger Probe BLUPRO Series Adult & Child Cable 1.6m (#P225F/TL-201T)",
        description: "Nihon Kohden BLUPRO Series reusable finger probe.",
        manufacturer: "BluPro / Nihon Kohden",
        equipmentModels: ["Nihon Kohden BSM-3500", "Nihon Kohden BSM-6500"],
        inStock: 0,
        unitPrice: 12400.00,
        minStock: 2,
        maxStock: 25,
        reorderPoint: 5,
        reorderQty: 10,
        location: "Cabinet B - Shelf 1 - Box 02",
        supplierName: "SR Science & Service Co., Ltd. (ร้านเอสอาร์.ชายน์แอนด์เซอร์วิส)",
        supplierContact: "081-589-4409",
        purchaseDate: "2024-12-04",
        expiryDate: "2027-06-04",
        leadTime: 21,
        repairFreq: 3,
      },
      {
        code: "SR-SPO2-005",
        name: "Adult Soft SpO2 Sensor Original Philips (#M1191 B/BL)",
        description: "Philips reusable silicon soft SpO2 sensor.",
        manufacturer: "Philips",
        equipmentModels: ["Philips IntelliVue MX450", "Philips Goldway G40"],
        inStock: 0,
        unitPrice: 10000.00,
        minStock: 3,
        maxStock: 30,
        reorderPoint: 6,
        reorderQty: 15,
        location: "Cabinet C - Shelf 1 - Box 01",
        supplierName: "SR Science & Service Co., Ltd. (ร้านเอสอาร์.ชายน์แอนด์เซอร์วิส)",
        supplierContact: "081-589-4409",
        purchaseDate: "2024-12-04",
        expiryDate: "2027-12-04",
        leadTime: 14,
        repairFreq: 5,
      },
      {
        code: "SR-SPO2-006",
        name: "Adult Finger SpO2 Sensor Original Philips (#M1196 A)",
        description: "Philips reusable finger clip SpO2 sensor.",
        manufacturer: "Philips",
        equipmentModels: ["Philips IntelliVue MX450", "Philips Goldway G40"],
        inStock: 0,
        unitPrice: 7800.00,
        minStock: 2,
        maxStock: 20,
        reorderPoint: 4,
        reorderQty: 10,
        location: "Cabinet C - Shelf 1 - Box 02",
        supplierName: "SR Science & Service Co., Ltd. (ร้านเอสอาร์.ชายน์แอนด์เซอร์วิส)",
        supplierContact: "081-589-4409",
        purchaseDate: "2024-12-04",
        expiryDate: "2027-12-04",
        leadTime: 14,
        repairFreq: 3,
      },
      {
        code: "SR-SPO2-007",
        name: "Adult Finger SpO2 Sensor for Mindray BD9 Standard (#512F)",
        description: "Mindray compatible SpO2 sensor with BD9 pin configuration.",
        manufacturer: "Mindray",
        equipmentModels: ["Mindray BeneVision N12", "Mindray BeneView T8"],
        inStock: 0,
        unitPrice: 4750.00,
        minStock: 10,
        maxStock: 100,
        reorderPoint: 20,
        reorderQty: 50,
        location: "Cabinet D - Shelf 2 - Box 01",
        supplierName: "SR Science & Service Co., Ltd. (ร้านเอสอาร์.ชายน์แอนด์เซอร์วิส)",
        supplierContact: "081-589-4409",
        purchaseDate: "2024-12-04",
        expiryDate: "2027-12-04",
        leadTime: 10,
        repairFreq: 10,
      },
      {
        code: "001CM02002",
        name: "Compatible Mindray Extension cable to Nellcor Oximax (SA-148-101)",
        description: "Extension cable connecting Mindray monitors to Nellcor Oximax sensors.",
        manufacturer: "Bangkok Medical Pro Co., Ltd. (บริษัท แบงค็อก เมดิคอล โปร จำกัด)",
        equipmentModels: ["Mindray BeneVision N12", "Nellcor PM10N"],
        inStock: 0,
        unitPrice: 3000.00,
        minStock: 1,
        maxStock: 10,
        reorderPoint: 3,
        reorderQty: 5,
        location: "Cabinet D - Shelf 3 - Box 01",
        supplierName: "Bangkok Medical Pro Co., Ltd.",
        supplierContact: "02-511-xxxx",
        purchaseDate: "2025-10-06",
        expiryDate: "2028-10-06",
        leadTime: 7,
        repairFreq: 2,
      },
      {
        code: "001CM02003",
        name: "Compatible SpO2 Extension cable, 7 Pin for Mindray (SA-048-001)",
        description: "7-pin SpO2 extension cable for Mindray monitors.",
        manufacturer: "Bangkok Medical Pro Co., Ltd. (บริษัท แบงค็อก เมดิคอล โปร จำกัด)",
        equipmentModels: ["Mindray BeneVision N12", "Mindray BeneView T8"],
        inStock: 0,
        unitPrice: 3000.00,
        minStock: 2,
        maxStock: 20,
        reorderPoint: 4,
        reorderQty: 10,
        location: "Cabinet D - Shelf 3 - Box 02",
        supplierName: "Bangkok Medical Pro Co., Ltd.",
        supplierContact: "02-511-xxxx",
        purchaseDate: "2025-10-06",
        expiryDate: "2028-10-06",
        leadTime: 7,
        repairFreq: 4,
      },
      {
        code: "001CM02008",
        name: "Compatible Extension cable for Nihon Kohden (SA-036-016)",
        description: "Extension cable compatible with Nihon Kohden bedside monitors.",
        manufacturer: "Bangkok Medical Pro Co., Ltd. (บริษัท แบงค็อก เมดิคอล โปร จำกัด)",
        equipmentModels: ["Nihon Kohden BSM-3500", "Nihon Kohden BSM-6500"],
        inStock: 0,
        unitPrice: 3000.00,
        minStock: 2,
        maxStock: 20,
        reorderPoint: 4,
        reorderQty: 10,
        location: "Cabinet B - Shelf 2 - Box 01",
        supplierName: "Bangkok Medical Pro Co., Ltd.",
        supplierContact: "02-511-xxxx",
        purchaseDate: "2025-10-06",
        expiryDate: "2028-10-06",
        leadTime: 7,
        repairFreq: 3,
      },
      {
        code: "001CM02004",
        name: "Compatible GE SpO2 Extension cable to Masimo encrypted (SA-421-149)",
        description: "GE interface extension cable to Masimo encrypted SpO2 sensors.",
        manufacturer: "Bangkok Medical Pro Co., Ltd. (บริษัท แบงค็อก เมดิคอล โปร จำกัด)",
        equipmentModels: ["GE Carescape B650", "Masimo Radical-7"],
        inStock: 0,
        unitPrice: 3000.00,
        minStock: 2,
        maxStock: 20,
        reorderPoint: 4,
        reorderQty: 10,
        location: "Cabinet A - Shelf 3 - Box 01",
        supplierName: "Bangkok Medical Pro Co., Ltd.",
        supplierContact: "02-511-xxxx",
        purchaseDate: "2025-10-06",
        expiryDate: "2028-10-06",
        leadTime: 7,
        repairFreq: 3,
      }
    ];

    const INITIAL_EQUIPMENT = [
      { serial: "NKP-BSM-001", model: "Nihon Kohden BSM-3500", dept: "ICU 1", value: 350000.00 },
      { serial: "NKP-BSM-002", model: "Nihon Kohden BSM-3500", dept: "ICU 1", value: 350000.00 },
      { serial: "NKP-BSM-003", model: "Nihon Kohden BSM-6500", dept: "OR 2", value: 580000.00 },
      { serial: "NKP-MX450-101", model: "Philips IntelliVue MX450", dept: "ER", value: 420000.00 },
      { serial: "NKP-MX450-102", model: "Philips IntelliVue MX450", dept: "ER", value: 420000.00 },
      { serial: "NKP-MX450-103", model: "Philips IntelliVue MX450", dept: "CCU", value: 420000.00 },
      { serial: "NKP-N12-201", model: "Mindray BeneVision N12", dept: "IPD 5", value: 280000.00 },
      { serial: "NKP-N12-202", model: "Mindray BeneVision N12", dept: "IPD 5", value: 280000.00 },
      { serial: "NKP-B650-301", model: "GE Carescape B650", dept: "Pediatric ICU", value: 500000.00 },
      { serial: "NKP-RAD7-401", model: "Masimo Radical-7", dept: "NICU", value: 250000.00 }
    ];

    const INITIAL_TRANSACTIONS = [];

    const INITIAL_PM_PLANS = [];
